[project]
authors = [
 {name = "Erik Leclercq", email = "erik.leclercq@cvrez.cz"}
 {name = "Jan Blažek", email = "todo@asap.com"}
]
description = "Registering videos of concrete samples"
readme = "README.md"



